sudo: false
language: ruby
rvm:
- 2.1.7
install:
- travis_retry bundle install
- travis_retry npm install -g grunt-cli
- travis_retry npm install -g bower
before_script:
- rvm install 2.1.7
- rvm use 2.1.7 --fuzzy
- npm install
- bower install
script:
- grunt build
after_success:
- sh deploy.sh