gems: ["jekyll-paginate"]
paginate: 9
paginate_path: "/posts/page:num/"
permalink: "/posts/:title/"
url: "www.umespressoumdia.cf"
baseurl: "/umespressoumdia"
markdown: "Kramdown"
title: Um espresso, um dia.
encoding: UTF-8

flickr:
  api_key: 1a5ba1193f156aa871e5f0f456109186

exclude: [
    'README.md',
    'package.json',
    'Gruntfile.js',
    'node_modules',
    'Gemfile*',
    'assets/sass',
    'assets/vendor'
]
